### ISSUE TITLE
Multi site with site-specific assets

### ISSUE THREAD

**Issue by ludwi** [vnbaaij/ImageProcessor.Web.Episerver#22]
Hi,

When we're using this package in an installation with more than one site with site-specific assets checked no images are being cropped except for the site with a wildcard hostname. Images placed in the globalassets folder are working though. We're using the latest version of everything.

Any idea how this can be resolved or if we need to do any special configuration for this case?

Thanks!

**Comment by vnbaaij** [comment]
As far as I know, no special configuration should be needed. The image below is coming from a siteassets folder as you can see. I tested this just now in the AlloyDemoKit microsite after checking the site-specific assets. Are you sure all the methods you are using to process the image are enabled in the processing.config file?
![image](https://user-images.githubusercontent.com/1761079/52861164-ec5a2500-3131-11e9-8e0c-e23724398b01.png)

**Comment by ludwi** [comment]
Thank you Vincent, 

You're right, I found out that it's working on my local machine, but when switching over from DiskCache to EpiserverAzureBlobCache and running it on Azure (DXC) the problem occurs.

**Comment by ludwi** [comment]
Sorry, but why is this issue closed? Isn't EpiserverAzureBlobCache supposed to work with multi sites and site-specific asset folders? Or have you confirmed that it actually work in an Azure environment? 

Thank you.

**Comment by vnbaaij** [comment]
Sorry, thought you meant it was solved. Will check how it works on Azure, but pretty sure it does. The cache should be kind of 'later' in the process

**Comment by vnbaaij** [comment]
It seems that there is a problem with the EpiserverImageProcessingModule detecting that it should process an image on Azure when there are multiple sites. Could you try something to test this? Please change the security.config file so that the <service> entry has a setting: 
```
<service name="AzureImageService" type="ImageProcessor.Web.Episerver.ImageService, ImageProcessor.Web.Episerver" >
      <settings>
        <setting key="MaxBytes" value="8194304"/>
      </settings>
    </service>
```
Doesn't really matter what is in the setting. Let me know if it works after you have tried with this change please

**Comment by ludwi** [comment]
I tried what you suggested but it didn't resolve the issue. I've also tried to override the GetRequestUrl method in EpiserverImageProcessingModule, returning both PathAndQuery or AbsoluteUri but neither of those seems to be the problem. 

Thank you for investigating!

**Comment by vnbaaij** [comment]
Hmm, stange. At least that change does resolve the problem in my testsite setup. I've pushed an update (5.3.2) to the feed.
Don't really know where else to look. Sorry.

**Comment by ludwi** [comment]
Vincent, you were right again! I had two services named AzureImageService in my security.config and I only added the setting to the last of them. After I removed the first it's working indeed. Doh! 

Thank you for your fast support and for a brilliant package!

**Comment by vnbaaij** [comment]
Glad you like it and got it working.
